/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmailQueueRouteImport } from './routes/email-queue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as SettingsGmailRouteImport } from './routes/settings.gmail'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsSendingRouteImport } from './routes/settings.sending'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailQueueRoute = EmailQueueRouteImport.update({
  id: '/email-queue',
  path: '/email-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGmailRoute = SettingsGmailRouteImport.update({
  id: '/settings/gmail',
  path: '/settings/gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSendingRoute = SettingsSendingRouteImport.update({
  id: '/settings/sending',
  path: '/settings/sending',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/email-queue': typeof EmailQueueRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/gmail': typeof SettingsGmailRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sending': typeof SettingsSendingRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/email-queue': typeof EmailQueueRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/gmail': typeof SettingsGmailRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sending': typeof SettingsSendingRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/email-queue': typeof EmailQueueRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/leads/$id': typeof LeadsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/gmail': typeof SettingsGmailRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sending': typeof SettingsSendingRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/email-queue'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/campaigns/$id'
    | '/leads/$id'
    | '/settings/ai'
    | '/settings/gmail'
    | '/settings/profile'
    | '/settings/sending'
    | '/campaigns/'
    | '/leads/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/email-queue'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/campaigns/$id'
    | '/leads/$id'
    | '/settings/ai'
    | '/settings/gmail'
    | '/settings/profile'
    | '/settings/sending'
    | '/campaigns'
    | '/leads'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/email-queue'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/campaigns/$id'
    | '/leads/$id'
    | '/settings/ai'
    | '/settings/gmail'
    | '/settings/profile'
    | '/settings/sending'
    | '/campaigns/'
    | '/leads/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  EmailQueueRoute: typeof EmailQueueRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  LeadsIdRoute: typeof LeadsIdRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsGmailRoute: typeof SettingsGmailRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSendingRoute: typeof SettingsSendingRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-queue': {
      id: '/email-queue'
      path: '/email-queue'
      fullPath: '/email-queue'
      preLoaderRoute: typeof EmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/gmail': {
      id: '/settings/gmail'
      path: '/settings/gmail'
      fullPath: '/settings/gmail'
      preLoaderRoute: typeof SettingsGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sending': {
      id: '/settings/sending'
      path: '/settings/sending'
      fullPath: '/settings/sending'
      preLoaderRoute: typeof SettingsSendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  EmailQueueRoute: EmailQueueRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  LeadsIdRoute: LeadsIdRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsGmailRoute: SettingsGmailRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSendingRoute: SettingsSendingRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
